
### model
model_name_or_path: /scratch/kalarde/Meta-Llama-3-8B-Instruct

### method
stage: come
do_train: true
do_predict: true
finetuning_type: full
trust_remote_code: true

### ttl parameters
setting: offline_come

### dataset
dataset: math_5k #colota #gsm8k_5k
eval_dataset: math_5k #colota #gsm8k_5k

# template: llama2
# template: qwen
template: llama3
cutoff_len: 1024
max_samples: 41000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b/offline_come/math

logging_steps: 10
save_steps: 8000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1 
learning_rate: 5.0e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
do_eval: null

### predict
temperature: 0.0
top_p: 1.0
do_sample: false
max_new_tokens: 512
per_device_eval_batch_size: 1
predict_with_generate: true

report_to: none